export const BASKET_ADD_ITEM = "BASKET_ADD_ITEM";
export const BASKET_REMOVE_ITEM = "BASKET_REMOVE_ITEM";
export const BASKET_SAVE_DELIVERY_ADDRESS = "BASKET_SAVE_DELIVERY_ADDRESS";
export const BASKET_SAVE_PAYMENT_METHOD = "BASKET_SAVE_PAYMENT_METHOD";

export const BASKET_OPTIONS_SET = "BASKET_OPTIONS_SET";
export const BASKET_OPTIONS_UPDATE = "BASKET_OPTIONS_UPDATE";
export const BASKET_OPTIONS_RESET = "BASKET_OPTIONS_RESET";
