export const BASKET_ADD_ITEM = "BASKET_ADD_ITEM";
export const BASKET_REMOVE_ITEM = "BASKET_REMOVE_ITEM";
export const BASKET_UPDATE_DELIVERY_METHOD = "BASKET_UPDATE_DELIVERY_METHOD";
export const BASKET_UPDATE_DELIVERY_COST = "BASKET_UPDATE_DELIVERY_COST";
export const BASKET_SAVE_DELIVERY_ADDRESS = "BASKET_SAVE_DELIVERY_ADDRESS";
export const BASKET_SAVE_PAYMENT_METHOD = "BASKET_SAVE_PAYMENT_METHOD";
export const BASKET_ITEMS_RESET = "BASKET_ITEMS_RESET";

export const BASKET_OPTIONS_SET = "BASKET_OPTIONS_SET";
export const BASKET_OPTIONS_UPDATE = "BASKET_OPTIONS_UPDATE";
export const BASKET_OPTIONS_RESET = "BASKET_OPTIONS_RESET";
export const BASKET_OPTIONS_CALC_COST = "BASKET_OPTIONS_CALC_COST";
